### ISSUE TITLE
Can't add any programs in Windows 10

### ISSUE THREAD

**Issue by Steve-Bros** [ahkohd/switch-desktop#48] opened 2020-03-04 22:11 UTC
OS: Windows 10 Home
2 monitors

I decided to install this program very recently, but whenever I try to add an .exe file, this happens.

![image](https://user-images.githubusercontent.com/40872506/75927678-71de6f00-5e32-11ea-8017-7521e2ac9258.png)

![image](https://user-images.githubusercontent.com/40872506/75927740-933f5b00-5e32-11ea-8ce6-f2b8dee9008f.png)

This completely defeats the purpose of the program, but I like the concept, so any assistance would be greatly appreciated.

**Comment by ahkohd** [comment] 2020-03-05 12:04
Hi, @Steve-Bros Have you tried adding other programs other than eclipse?

**Comment by Steve-Bros** [comment] 2020-03-05 16:09
I have. I tried to add programs like Microsoft Edge Chromium and Notepad++, along with some portable programs. No .exe file works.

**Comment by ahkohd** [comment] 2020-03-12 16:30
@Steve-Bros  any update?

**Comment by Steve-Bros** [comment] 2020-03-12 17:16
Sadly, no updates. My main problem is that this is my only computer. I tried reinstalling the software with administrator mode, but still nothing. Sorry.

**Comment by ahkohd** [comment] 2020-03-12 17:33
@Steve-Bros thanks. I will investigate further after I dual-boot my mac with 
Windows 10.

**Comment by Jack-Chronicle** [comment] 2020-03-15 06:25
I'm having the same issue here, really hoping it can be fixed easily cause this look super amazing

**Comment by ahkohd** [comment] 2020-03-15 11:24
@Jack-Chronicle @Steve-Bros Thanks a lot for reporting this issue.
Please try v1.0.25 https://github.com/ahkohd/switch-desktop/releases/download/v1.0.25/Switch-Setup-1.0.25.exe

It's funny that I have forgotten why I haven't made this version public yet, but it seems it contains the fix to the reported issue as it works.
Please help me out by testing ASAP so that I can update the link at the homepage.

Thanks!

**Comment by DylanAkp** [comment] 2020-03-22 17:44
Same issue here, already with the v1.0.25

**Comment by ahkohd** [comment] 2020-03-23 20:43
> Same issue here, already with the v1.0.25

I worked on the last Windows10 system I tried it on. I wonder what is wrong, I will try and investigate tomorrow as soon as I lay my hands on a Windows10 system.

**Comment by ahkohd** [comment] 2020-03-23 20:56
I think I have found what the issue is.
<img width="1072" alt="Screenshot 2020-03-23 at 21 49 32" src="https://user-images.githubusercontent.com/13041443/77361859-52ab7100-6d50-11ea-89bc-8a225c62a972.png">

According to http://mimeapplication.net/x-msdownload the said the `content-type` of a `.exe` can be one out of `application/x-msdownload`, `application/octet-stream` and `application/x-msdos-program`.

but in my code, I only check if the content type is `application/x-msdownload`

![image](https://user-images.githubusercontent.com/13041443/77361950-7373c680-6d50-11ea-87f7-3cce16b3a1d3.png)

**Comment by ahkohd** [comment] 2020-03-23 20:59
As a matter of fact, content types related to to `` are 
```ts
let exeRelatedContentTypes = ['application/bin',
'application/binary',
'application/com',
'application/dos-exe',
'application/exe',
'application/macbinary',
'application/msdos-windows',
'application/octet-stream',
'application/x-com',
'application/x-exe',
'application/x-macbinary',
'application/x-msdos-program',
'application/x-stuffit',
'application/x-tencore',
'application/x-winexe',
'application/x-zip-compressed',
'vms/exe',
]
```

**Comment by ahkohd** [comment] 2020-03-23 23:05
@Steve-Bros @Jack-Chronicle @DylanAkp 😉I just fixed the issue. PR #51 ships the fix to the bug.
You can download the update from the [home page.]( https://ahkohd.github.io/switch-desktop)

**Comment by DylanAkp** [comment] 2020-03-24 08:55
Fixed for me, thank you for your work !

**Comment by ahkohd** [comment] 2020-03-25 10:17
Can anyone confirm this before I close this issue?

**Comment by DylanAkp** [comment] 2020-03-25 10:20
Working perfectly, thank you!

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Closed** 2020-03-25 10:21 UTC
Labels: bug
